apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clients.shoplift.example.com
spec:
  group: shoplift.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                xmlConfig:
                  type: string
              required:
                - xmlConfig
            status:
              type: object
  scope: Namespaced
  names:
    plural: clients
    singular: client
    kind: Client
    shortNames:
      - cl